#!/usr/bin/env bash

cd ~/Downloads/ || exit

rm -rf /usr/local/nvim/* &&
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz &&
tar -xvzf nvim-macos.tar.gz &&
mv nvim-macos/* /usr/local/nvim/ &&

test -f 'nvim-macos.tar.gz' && trash nvim-macos.tar.gz
test -d 'nvim-macos' && trash nvim-macos
