#!/usr/bin/env bash

cd ~/Downloads/ || exit

file=nvim-macos-x86_64

rm -rf /usr/local/nvim/* &&
  curl -LO https://github.com/neovim/neovim/releases/download/nightly/"$file".tar.gz &&
  tar -xvzf "$file".tar.gz &&
  mv "$file"/* /usr/local/nvim/ &&
  test -f "$file".tar.gz && trash "$file".tar.gz
test -d "$file" && trash "$file"
